controllers/CadenabastecimientoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cadenadeabastecimiento;
use app\models\VwTotalIndicadoresCa;
use app\models\VwTotalIndicadoresCaSearch;
use app\models\VwIdlPedidosSearch;

class CadenabastecimientoController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii2mod\rbac\filters\AccessControl::class,
                'allowActions' => [
                ]
            ],
        ];
    }
    
    public function actionEficienciadespachoaduanero()
    {
        return $this->render('eficienciadespachoaduanero');
    }

    public function actionEficienciaempresatransporte()
    {
        return $this->render('eficienciaempresatransporte');
    }

    public function actionEficienciapuertos()
    {
        return $this->render('eficienciapuertos');
    }

    public function actionEficienciazonafranca()
    {
        return $this->render('eficienciazonafranca');
    }

    public function actionTiempoca()
    {
        if(Yii::$app->request->get('idca')){
            return $this->render('tiempoca');
        }else{
            throw new Exception("El id de la cadena de abastecimiento se debe enviar, para su carga.", 1);
        }
    }

    public function actionGestionarcadena($id)
    {
        //Yii::$app->cache->flush();

        $cadena = $this->findModel($id);
        $etapas = [];
        //print_r($e);die;
        if( Yii::$app->request->get('secccion') == 'actualizar_cadena' ) {
            array_unshift($etapas, [
                'label' => 'Cadena',
                'content' => $this->renderPartial('actualizar', [
                            'model' => $cadena,
                            ]),
                'active' => true
            ]);
        }else{
            array_unshift($etapas, [
                'label' => 'Cadena',
                'url' => \yii\helpers\Url::to(['cadenabastecimiento/gestionarcadena', 'id'=>$id, 'secccion' => 'actualizar_cadena'])
            ]);
        }

        foreach (\app\models\Etapa::find()->all() as $e) {
             $k = [
                'label' => $e->ETAPA,
                'url' => \yii\helpers\Url::to(['cadenabastecimiento/gestionarcadena', 'id'=>$id, 'etapa' => $e->ID_ETAPA, 'secccion' => 'proceso']),
            ];
            if(Yii::$app->request->get('etapa')==$e->ID_ETAPA){
                $k["active"] = true;
                if( is_null($cadenaEtapa = \app\models\CadenaEtapa::find()->where(['ID_ETAPA' => $e->ID_ETAPA, 'ID_CADENA' =>  $id])->one()) ){
                    $cadenaEtapa = new \app\models\CadenaEtapa();
                    $cadenaEtapa->ID_ETAPA = $e->ID_ETAPA;
                    $cadenaEtapa->ID_CADENA = $id;
                    $cadenaEtapa->save();
                }
                $dataProvider = new \yii\data\ActiveDataProvider([
                    'query' => \app\models\CadenaIndicador::find()->where(['ID_CADENA' => $cadenaEtapa->ID_ETP_CAD]),
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                ]);
                $k["content"] = $this->renderPartial('etapa_cadena', [
                                    'model' => $cadenaEtapa,
                                    'cadena' => $cadena,
                                    'dataProvider' => $dataProvider
                                ]);

            }
            $etapas[] = $k;
        }

        if(Yii::$app->request->get('secccion') == 'resultado_indicadores') {
            $searchModel = new VwTotalIndicadoresCaSearch();
            $searchModel->ID_CADENA = Yii::$app->request->get('id');
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $etapas[] = [
                    'label' => 'Resultado de indicadores',
                    'content' => $this->renderPartial('total_indicadores_ca', [
                                'model' => $cadena,
                                'searchModel' => $searchModel,
                                'dataProvider' => $dataProvider,
                                ]),
                    'active' => true
                ];
        }else{
            $etapas[] = [
                'label' => 'Resultado de indicadores',
                'url' => \yii\helpers\Url::to(['cadenabastecimiento/gestionarcadena', 'id'=>$id, 'secccion' => 'resultado_indicadores'])
            ];
        }

        if(Yii::$app->request->get('secccion') == 'idl_pedidos') {
            //$searchModel = new \app\models\CadenaEtapaSearch();
            //$searchModel->ID_CADENA = Yii::$app->request->get('id');
            //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $Metapas = \app\models\Etapa::find()->all();
            $cadena = $this->findModel(Yii::$app->request->get('id'));
            $arr = [];
            $i = 0;
            foreach ($cadena->pEDIDOS as $row) {
               $arr[] = [
                    'DS_CODIGO_PEDIDO' => $row->DS_CODIGO_PEDIDO
               ];
               foreach ($Metapas as $etapa) {
                    $MCadenaEtapa = \app\models\CadenaEtapa::find()->with(['cadenaIndicadors'=>function($m) use ($row){
                        $m->where(['ID_PEDIDO' => $row->CS_PEDIDO_ID]);
                    }])->where(['ID_ETAPA' => $etapa->ID_ETAPA, 'ID_CADENA' => Yii::$app->request->get('id')])->one();
                    //echo "<pre>"; print_r($MCadenaEtapa);die;
                    $N = 0;
                    $S  = 0;
                    /*if (!is_object($MCadenaEtapa)) {
                        echo $row->CS_PEDIDO_ID;
                        echo "<br/>".$etapa->ID_ETAPA;die;
                    } */
                    if (is_object($MCadenaEtapa)) {
                        foreach ($MCadenaEtapa->cadenaIndicadors as $r) {
                            if($r->iNDICADOR->NM_ID_TIPO_IND == 2 || $r->iNDICADOR->NM_ID_TIPO_IND == 3){
                                $S += $r->NM_RESULTADO_INDICADOR/((empty($r->META) || $r->META == 0)?1:$r->META);
                            }else{
                                $S += $r->NM_RESULTADO_INDICADOR;
                            }
                            $N++;
                        }
                        # code...
                    }
                    $arr[$i][trim($etapa->ETAPA.$etapa->ID_ETAPA)] = round(($N>0?(($S/$N)):0)*100, 3)."%";
                   //round($model->CUMPLIMIENTO_PROMEDIO*100, 3)
               }
               $i++;
            }

            $dataProvider=new \yii\data\ArrayDataProvider([
                'key' => 'DS_CODIGO_PEDIDO',
                'sort'=>['attributes'=>['DS_CODIGO_PEDIDO'],],
                'allModels' => $arr,
                'pagination'=>['pageSize'=>1000]
                ]
            );

        //    echo "<pre>";print_r($arr);die;

            $etapas[] = [
                    'label' => 'Cumplimiento por pedido',
                    'content' => $this->renderPartial('idl_pedidos_ca', [
                                'model' => $cadena,
                                'etapas' => $Metapas, 
                                //'searchModel' => $searchModel,
                                'dataProvider' => $dataProvider,
                                ]),
                    'active' => true
                ];
        }else{
            $etapas[] = [
                'label' => 'Cumplimiento por pedido',
                'url' => \yii\helpers\Url::to(['cadenabastecimiento/gestionarcadena', 'id'=>$id, 'secccion' => 'idl_pedidos'])
            ];
        }

        if(Yii::$app->request->get('secccion') == 'complimiento_proceso') {
            $searchModel = new \app\models\CadenaEtapaSearch();
            $searchModel->ID_CADENA = Yii::$app->request->get('id');
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $etapas[] = [
                    'label' => 'IDL del Proceso',
                    'content' => $this->renderPartial('cumplimiento_proceso', [
                                'model' => $cadena,
                                'searchModel' => $searchModel,
                                'dataProvider' => $dataProvider,
                                ]),
                    'active' => true
                ];
        }else{
            $etapas[] = [
                'label' => 'IDL del Proceso',
                'url' => \yii\helpers\Url::to(['cadenabastecimiento/gestionarcadena', 'id'=>$id, 'secccion' => 'complimiento_proceso'])
            ];
        }
        //echo "<pre>";print_r($etapas);die;
        if ($cadena->load(Yii::$app->request->post()) && $cadena->save()) {
            Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                        'duration' => 5000,
                        'icon' => 'fa fa-users',
                        'message' => Yii::t('app', \yii\bootstrap\Html::encode('La cadena fue actualizada correctamente.')),
                        'title' => Yii::t('app', \yii\bootstrap\Html::encode('Creación')),]);
                return $this->redirect(['gestionarcadena', 'id' => $cadena->NM_CADENA_ID, 'secccion' => 'actualizar_cadena']);
        }
         return $this->render('gestrionar_cadena', [
            'cadena' => $cadena,
            'etapas' => $etapas
         ]);
    }

    public function actionConsultarcadenacontrato($id)
    {
        $cadena = $this->findModel($id);
        return $this->render('consultarcadenacontrato', [
            'cadena' => $cadena,
         ]);
    }

    public function actionEscribircadenacontrato($id)
    {
        $cadena = $this->findModel($id);
        return $this->render('escribircadenacontrato', [
            'cadena' => $cadena,
         ]);
    }

    public function actionVerca()
    {
        $searchModel = new \app\models\CadenadeabastecimientoSearch();

views/cadenabastecimiento/_frm_vercadena.php
<center><h4>TIEMPO DE LA GESTIÓN DE LA CADENA DE SUMINISTRO</h4>
<h5>Proceso:  Tiempo del pedido desde la orden de compra, hasta la receptión de la mercancia en destino final</h5>


<table class="table table-bordered">
	<tr>
		<td>NOMBRE EMPRESA</td><td>PEDIDO</td>
	</tr>
	<tr>
		<td></td> <td></td>
	</tr>
	<tr>
		<td>FECHA INICIO</td><td>FECHA FIN </td>
	</tr>
	<tr>
		<td></td> <td></td>
	</tr>
	<tr>
		<td colspan="2" style="text-align: center;">TIEMPO TRASCURRIDO</td>
	</tr>
	<tr> <td colspan="2"></td> </tr>
	<tr>
		<td colspan="2" style="text-align: center;">EN MESES</td>
	</tr>
	<tr> <td></td><td></td> </tr>
	<tr>
		<td colspan="2" style="text-align: center;">EN DIAS</td>
	</tr>
	<tr> <td></td><td></td> </tr>
	<tr>
		<td colspan="2" style="text-align: center;">EN HORAS</td>
	</tr>
	<tr> <td></td><td></td> </tr>
</table>

</center>

views/cadenabastecimiento/_indicador.php
<?php if($index%2==0){ 
     $this->registerJs("
                $('input[rel=\"txtTooltip\"]').tooltip(); 
                ");
    ?>
    <div class="row">
<?php
} ?>
<div class="col-md-6"> 
          <!-- DIRECT CHAT PRIMARY -->
          <div class="box box-success direct-chat direct-chat-success">
            <div class="box-header with-border">
              <h3 class="box-title"><?= $model->iNDICADOR->DS_NOMBRE_INDICADOR ?></h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool btn_ocultar" data-widget="remove" style="display: none"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool btn_eliminar_indicador"><i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-box-tool duplicar" title="duplicar" ID_INDICADOR=<?= $model->ID_INDICADOR ?> ID_ETP_CAD=<?= $model->ID_CADENA ?>><i class="fa fa-clone"></i>
                </button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             	<div class="table-responsive">
             		<form class="frm_indicador">
             		<table formula="<?= $model->iNDICADOR->DS_FORMULA ?>" NM_ID_TIPO_IND="<?= $model->iNDICADOR->NM_ID_TIPO_IND ?>" class="table table-bordered">
             			<tr>
             				<th>Definición</th>
             				<th>Area</th>
             				<th>Indicador</th>
             				<th>Nomenclatura</th>
             			</tr>
             			<tr>
             				<td><?= $model->iNDICADOR->DEFINICION ?></td>
             				<td><?= $model->iNDICADOR->aREA->DS_AREA ?></td>
             				<td><?= $model->iNDICADOR->DS_NOMBRE_INDICADOR ?></td>
             				<td><?= $model->iNDICADOR->DS_NOMENCLATURA ?></td>
             			</tr>
             			<tr>
             				<td colspan="4">
             					<?php 
             						foreach (explode('%', $model->iNDICADOR->DS_FORMULA) as $val) {
					                    if (is_numeric($val)) {
					                    	//die($val);
					                    	$campoCadena = \app\models\CampoCadenaIndicador::find()->where(['ID_CAMPO' => $val,'ID_CADENA_INDICADOR'=>$model->ID_INDICADOR_CADENA])->one();
					                        if(is_null($campoCadena)) {
						                        $campo = \app\models\CampoCaculo::find()->where(["ID_CAMPO"=>$val])->one();
						                        $model->iNDICADOR->DS_FORMULA = str_replace('%'.$val.'%', ' <input type="number" name="CampoCadenaIndicador['.$val.']" style="width: 20%;display: inline-block;" class="form-control campo_formula" idcampo="'.$campo->ID_CAMPO.'" data-toggle="tooltip" title="'.$campo->DS_CAMPO_CALCULO.'" rel="txtTooltip"/> ', $model->iNDICADOR->DS_FORMULA);
					                        }else{
					                        	$model->iNDICADOR->DS_FORMULA = str_replace('%'.$val.'%', ' <input type="number" value="'.$campoCadena->VALOR.'" name="CampoCadenaIndicador['.$val.']" style="width: 20%;display: inline-block;" class="form-control campo_formula" idcampo="'.$campoCadena->cAMPO->ID_CAMPO.'" data-toggle="tooltip" title="'.$campoCadena->cAMPO->DS_CAMPO_CALCULO.'" rel="txtTooltip"/> ', $model->iNDICADOR->DS_FORMULA);
					                        }
					                    }
					                }
             						echo $model->iNDICADOR->DS_FORMULA;
             					?>
             				</td>
             			</tr>
             			<tr>
             				<td>Total Indicador: </td>
             				<td>
             					<span class="valor"><?php 
                                    if($model->iNDICADOR->NM_ID_TIPO_IND == 1){
                                        echo !empty($model->NM_RESULTADO_INDICADOR)?round($model->NM_RESULTADO_INDICADOR*100,3):0;
                                    }else{
                                        echo !empty($model->NM_RESULTADO_INDICADOR)?round($model->NM_RESULTADO_INDICADOR,3):0;
                                    }
                                ?></span>
             					<input type="hidden" name="CadenaIndicador[NM_RESULTADO_INDICADOR]" class="NM_RESULTADO_INDICADOR" value="<?= !empty($model->NM_RESULTADO_INDICADOR)?$model->NM_RESULTADO_INDICADOR:0?>">
             					<input type="hidden" name="CadenaIndicador[ID_INDICADOR_CADENA]" value="<?= $model->ID_INDICADOR_CADENA ?>">
             				</td>
                            <td colspan="2">
                                <b><?= $model->iNDICADOR->UNIDAD ?></b>
                            </td>
             			</tr>
             			<tr style="display: none;">
             				<td colspan="2"><?= $model->getAttributeLabel("NM_PORCENTAJE_SIGNIFICANCIA") ?>: <input  style="width: 60%;display: inline-block;" type="number" value="<?= !empty($model->NM_PORCENTAJE_SIGNIFICANCIA)?$model->NM_PORCENTAJE_SIGNIFICANCIA:0?>" name="CadenaIndicador[NM_PORCENTAJE_SIGNIFICANCIA]" class="form-control"></td>
                            
             			</tr> 
                        <tr>
                            <td><?= $model->getAttributeLabel("META") ?>: 
                                <input style="width: 80%;display: inline-block;" type="number" value="<?= !empty($model->META)?$model->META:0?>" name="CadenaIndicador[META]" class="form-control cadena_indicaro_meta">
                            </td>
                            <td colspan="3"><?= $model->getAttributeLabel("ID_PEDIDO") ?>:<br/> <select  style="display: inline-block;" name="CadenaIndicador[ID_PEDIDO]" class="form-control">
                                <option value=''></option>
                                <?php 
                                    if(!is_null($model->cADENAETAPA->cADENA) && !is_null($model->cADENAETAPA->cADENA->pEDIDOS)){
                                        foreach ($model->cADENAETAPA->cADENA->pEDIDOS as $pedido) { ?>
                                            <option <?php echo ($model->ID_PEDIDO == $pedido->CS_PEDIDO_ID?'selected':'')?> value="<?= $pedido->CS_PEDIDO_ID?>"><?= $pedido->DS_CODIGO_PEDIDO ?></option>
                                <?php   
                                        }   
                                    }
                                ?>
                            </select>
                            </td>
                        </tr>
                        <?php if($model->iNDICADOR->tIPOINDICADOR->ID_TIPO == 2 || $model->iNDICADOR->tIPOINDICADOR->ID_TIPO == 3){ ?>
                            <tr>
                                <td colspan="2">
                                    Porcentaje de cumplimiento
                                </td>
                                <td colspan="2">
                                    <span class="porcentaje_cumplimiento"><?= round(($model->NM_RESULTADO_INDICADOR/(!empty($model->META)?$model->META:1))*100,3) ?>%</span>
                                </td>
                            </tr>
                        <?php } ?>
             		</table> 
                    <input type="hidden" name="CadenaIndicador[IDCANDEABAS]" value="<?= $model->cADENAETAPA->cADENA->NM_CADENA_ID ?>">
             		</form>
         		</div>
              <!-- /.direct-chat-pane -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="input-group">
                  <button type="submit" class="btn btn-primary btn-flat btn_guardar_indicador">Guardar</button>
                </div>
            </div>
            <!-- /.box-footer-->
          </div>
          <!--/.direct-chat -->
        </div>
<?php if($index%2!=0){ ?>
    </div>
<?php
} ?>        

views/cadenabastecimiento/actualizar.php
<?php
/* @var $this yii\web\View */

$this->title = Yii::t('app', 'Cadena de abastecimiento de la empresa '.$model->iDEMPRESA->DS_NOMBRES_ACTOR);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cadena de abastecimiento'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;


echo $this->render('_form_ingreso', [
	'model' => $model,
]);

views/cadenabastecimiento/consultarcadenacontrato.php
<?php
$this->title = Yii::t('app', 'Consultar información de cadena sobre el contrato');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Listado'), 'url' => ['cadenabastecimiento/verca']];
$this->params['breadcrumbs'][] = $this->title;


?>

<script type="text/javascript">
	
	nodo.emit('consultar', "<?= $_GET['id']?>");
	
</script>
<div id="load" style="position: absolute;width: 83%; height: 100%;z-index:1;background: #474F4D;opacity: 0.5;"><center><img src="https://acegif.com/wp-content/uploads/loading-25.gif" style="margin-top:15%;width: 10%"></center></div>
<div id="idcanena" style="display:none"><?= $_GET['id']?></div>

<div class="cadena-etapa-form box box-primary">
    <div class="box-body table-responsive">
        <div class="form-row">

<table class="table table-bordered">
	<tr>
		<th>Id cadena</th>
		<td id="cadena"></td>
	</tr>
	<tr>
		<th>Cuenta - Documento o NIT</th>
		<td id="cuenta"></td>
	</tr>
	<tr>
		<th>Fecha de medición</th>
		<td id="fecha"></td>
	</tr>
	<tr>
		<th>Peididos</th>
		<td><ul id="pedidos"></ul></td>
	</tr>
	<tr>
		<th>
			Indicadores
		</th>
		<td>
		<table class="table table-bordered">
			<thead> <tr>
				<th>Pedido</th>
				<th>Indicador</th>
				<th>Resultado Indicador</th>
				<th>Meta</th>
				<th>Ponderación</th>
				<th>Unidad</th>
			</tr></thead>
			<tbody id="indicadores">
				
			</tbody>
		</table>
	</td>
	</tr>
</table>

</div>
</div>

</div>

views/cadenabastecimiento/cumplimiento_proceso.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\VwTotalIndicadoresCaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Total indicadores, cadena de '.$model->iDEMPRESA->DS_NOMBRES_ACTOR);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vw-total-indicadores-ca-index box box-primary">
    <?= Html::beginForm(['#'], 'post', ['enctype' => 'multipart/form-data', 'id' => 'total_etapas_frm']) ?>
    <?php Pjax::begin([
                        'id' => 'grid_cumplimiento_proceos',
                        'timeout' => 5000,
    ]); ?>

    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'showPageSummary' => true,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
               // 'eTTAPA',
                [
                    'label' => 'Actor',
                    'attribute'=> 'NOMBREACTORETAPA',
                    'value'=>'aCTOR.DS_NOMBRES_ACTOR',
                ],
                [
                    'label' => 'Proceso',
                    'attribute'=> 'NOMBREDELAETAPA',
                    'value'=>'eTAPA.ETAPA',
                ],
                [
                    'attribute' => 'CUMPLIMIENTO_PROMEDIO',
                    'value' => function($row){
                        return round($row->CUMPLIMIENTO_PROMEDIO*100, 3)."%";
                    }
                ],
                [
                    'filter' => false,
                    'attribute' => 'NM_PORCENTAJE_SIGNIFICANCIA',
                    'format' => 'raw',
                    'value' => function($data){

                        return "<div style='display: inline-block'>".\yii\bootstrap4\Html::textInput('CadenaEtapa[NM_PORCENTAJE_PONDERACION]['.$data->ID_ETP_CAD.']', $data->NM_PORCENTAJE_SIGNIFICANCIA, ['class' => 'form-control ponderacion_significancia'])."</div><div style='display: inline-block;margin-left:5px;'><span style='display:none' class='span_porcentaje_significancia'>".$data->NM_PORCENTAJE_SIGNIFICANCIA."</span>%</div>";
                        //empty($data->NM_PORCENTAJE_SIGNIFICANCIA)?"":$data->NM_PORCENTAJE_SIGNIFICANCIA."%";
                    }
                ],
                [
                    'attribute' => 'idl',
                    'value' => function($row){
                        return $row->CUMPLIMIENTO_PROMEDIO*($row->NM_PORCENTAJE_SIGNIFICANCIA/100);
                    },
                    'pageSummary' => function ($summary, $data, $widget) { return $summary; }
                ]
            ],
            'exportConfig' => [
                 GridView::PDF => [],
                  GridView::EXCEL => [],
            ],
            'pjax' => true,
            'bordered' => true,
            'striped' => false,
            'responsive' => true,
            'floatHeaderOptions' => ['scrollingTop' => '50'],
            'panel' => [
                'type' => GridView::TYPE_INFO   
            ],
        ]); ?>
    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('app', 'Guardar'), ['class' => 'btn btn-success btn-block', 'id' => 'btn_guargar_total_indicadores']) ?>
    </div>
    <?php Pjax::end(); ?>
    <?= Html::endForm() ?>
</div>

<?php 
    $this->registerJs("$(document).ready(function(e){ 
        $(document).on('change', '.ponderacion_significancia',function(e){
            
        });

        $(document).on('click', '#btn_guargar_total_indicadores',function(e){
            e.preventDefault();
            var t = this;
            var total = 0;
            $(this).css('pointer-events', 'none');
            $(this).parent().append(\"<img id='img_preload_modal' src='/dist/img/loading-plugin.gif'/>\");

             $('.ponderacion_significancia').each(function(e,r){ 
                $(r).parent().parent().find('.span_porcentaje_significancia').html($(r).val());
                total += (Number.isInteger($(r).val()) || isDecimal($(r).val()))?parseFloat($(r).val()):0; 
            }).promise().done(function(){
                if(total <= 100){ 
                    $.post('".yii\helpers\Url::to(['indicador/almacenarinformacioncumplimientoproceso'])."' ,$('#total_etapas_frm').serialize(), function(r){
                            if(r.respuesta){
                                $.notify({\"message\":r.mensaje,\"icon\":\"fa fa-cubes\",\"url\":\"\",\"target\":\"_blank\"}, {
                                                type: \"success\",
                                                align: \"right\",
                                                from: \"top\"
                                            });
                            }else{
                                $.notify({\"message\":r.mensaje,\"icon\":\"fa fa-cubes\",\"url\":\"\",\"target\":\"_blank\"}, {
                                            type: \"danger\",
                                            align: \"right\",
                                            from: \"top\"
                                        });
                            }
                            $('#img_preload_modal').remove();
                            $(t).css('pointer-events', 'auto');
                            $.pjax.reload({container: '#grid_cumplimiento_proceos', async:false});
                    }, 'JSON');
                }else{
                      $.notify({\"message\":'La ponderación no puede superar el 100%. La sumatoria total de momento es '+total+'%',\"icon\":\"fa fa-cubes\",\"url\":\"\",\"target\":\"_blank\"}, {
                            type: \"danger\",
                            align: \"right\",
                            from: \"top\"
                        }); 
                    $('#img_preload_modal').remove();
                    $(t).css('pointer-events', 'auto');
                }
            });
        });
    });

    function isDecimal(n){
        if(n == \"\")
            return false;

        var strCheck = \"0123456789\";
        var i;

        for(i in n){
            if(strCheck.indexOf(n[i]) == -1)
                return false;
        }
        return true;
    }");
?>

views/cadenabastecimiento/eficienciadespachoaduanero.php
<?php
/* @var $this yii\web\View */
?>
<h1>cadenabastecimiento/eficienciadespachoaduanero</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/cadenabastecimiento/eficienciaempresatransporte.php
<?php
/* @var $this yii\web\View */
?>
<h1>cadenabastecimiento/eficienciaempresatransporte</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/cadenabastecimiento/eficienciapuertos.php
<?php
/* @var $this yii\web\View */
?>
<h1>cadenabastecimiento/eficienciapuertos</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/cadenabastecimiento/eficienciazonafranca.php
<?php
/* @var $this yii\web\View */
?>
<h1>cadenabastecimiento/eficienciazonafranca</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>