controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Mailer as AcmeMailer;
use app\components\AuthHandler;

class SiteController extends Controller {

    public function actionBackup() {
        /** @var \demi\backup\Component $backup */
        $backup = \Yii::$app->backup;

        $file = $backup->create();

        return "Se creo el backup";
    }

    public function actionAcercade() {
        return $this->render('acercade');
    }

    public function actionAyuda()
    {
        return $this->render('ayuda');
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client) {
        (new AuthHandler($client))->handle();
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        //$l = new \yii\caching\FileCache();
        //$l->flushValues();

        //Yii::$app->cache->flush();

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionRecuperarPassword() {
        $Actor = new MathUser('registerwcaptcha');
        if (isset($_POST['MathUser'])) {
            $Actor->attributes = $_POST['MathUser'];
            //  print_r($_POST);die;
            $this->performAjaxValidation($Actor);
            //print_r($_POST);
            $u = $Actor->find('email=?', array($Actor->email));
            $this->enviarMailRecuperacionActor($u);
            $u->state = CRUGEUSERSTATE_RECOVERPASSWORD;
            $u->update();
            $user = Yii::app()->getComponent('user');
            Yii::app()->user->setFlash(
                    'success', "<strong>Exito!</strong> Se ha enviado un correo con la informacón para realizar este cambío."
            );
            $this->redirect(Yii::app()->getBaseUrl(true));
        }
    }

    public function actionRestaurarcredenciales() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new \app\models\Actor1(['scenario' => \app\models\Actor1::SCENARIO_TARE_CREDENTIALS]);
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post())) {
//            if (true) {
            if ($model->validate()) {
                $model = \app\models\Actor1::find()->where(["DS_CORREO" => $model->DS_CORREO])->one();
                if (AcmeMailer::send(AcmeMailer::TYPE_RESTAURAR_CONTRASENA, $model)) {
                    $model->NM_ESTADO_ID = \app\models\EstadoActor::PENDIENTE_RESTAURAR_CONTRASENA;
                    \app\models\Actor1::updateAll(['NM_ESTADO_ID' => \app\models\EstadoActor::PENDIENTE_RESTAURAR_CONTRASENA], ["ID_ACTOR" => $model->ID_ACTOR]);
                    Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                        'duration' => 5000,
                        'icon' => 'fa fa-users',
                        'message' => Yii::t('app', \yii\bootstrap\Html::encode('Se a enviado un correo para iniciar el proceso de recuperación de contraseña, mientras no se restaure no podrá iniciar sesión.')),
                        'title' => Yii::t('app', \yii\bootstrap\Html::encode('Envío de correo exitosa')),]);

                    return $this->redirect(["site/login"]);
                }
            } else {
                return $this->render('recuperar_contrasena', [
                            'model' => $model,
                ]);
            }
        } else {
            return $this->render('recuperar_contrasena', [
                        'model' => $model,
            ]);
        }
    }

    public function actionRegitrar() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new \app\models\Actor();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
        }


        if ($model->load(Yii::$app->request->post())) {
            $model->setAttribute("NM_ESTADO_ID", \app\models\EstadoActor::ACTIVO);
            $model->DT_FECHA_CREACION = date("Y-m-d");
            $model->NM_TIPO_ACTOR_ID = \app\models\TipoActor::ACTOR_NORMAL;
            //var_dump($model->attributes);
            if ($model->validate()) {
                $model->DS_CONTRASENA = $model->CONFIRMAR_CONTRASENA = Yii::$app->getSecurity()->generatePasswordHash($model->DS_CONTRASENA);
                if ($model->save() && AcmeMailer::send(AcmeMailer::TYPE_REGISTRATION, $model)) {
                    Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                        'duration' => 5000,
                        'icon' => 'fa fa-users',
                        'message' => Yii::t('app', \yii\bootstrap\Html::encode('El Actor fue registrado exitosamente.')),
                        'title' => Yii::t('app', \yii\bootstrap\Html::encode('Actor registrado')),]);

                    return $this->redirect(["site/login"]);
                }
            } else {
                return $this->render('registro', [
                            'model' => $model,
                ]);
            }
        } else {
            $model->NM_TIPO_DOCUMENTO_ID = "1";
            $model->NM_TIPO_ACTOR_ID = "2";
            return $this->render('registro', [
                        'model' => $model,
            ]);
        }
    }

    public function actionCambiocontrasena() {
//        print_r($_REQUEST);die;
        $model = new \app\models\Actor1();
        $model->scenario = \app\models\Actor1::SCENARIO_SAVE_TARE_CREDENTIALS;

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
        } else if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                 
                $model->NM_ESTADO_ID = \app\models\EstadoActor::ACTIVO;
                $model->ID_ACTOR = $_REQUEST["id"];
                $model->DS_CONTRASENA = $model->CONFIRMAR_CONTRASENA = Yii::$app->getSecurity()->generatePasswordHash($model->DS_CONTRASENA);
                if (\app\models\Actor1::updateAll(['DS_CONTRASENA' => $model->DS_CONTRASENA, 'NM_ESTADO_ID' => \app\models\EstadoActor::ACTIVO], ["ID_ACTOR" => $model->ID_ACTOR])) {
                    Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                        'duration' => 5000,
                        'icon' => 'fa fa-users',
                        'message' => Yii::t('app', \yii\bootstrap\Html::encode('Los datos de la cuenta fueron actualizados. El Actor fue activado y puede ingresar nuevamente al sistema sin problemas.')),
                        'title' => Yii::t('app', \yii\bootstrap\Html::encode('Contraseña restablecida')),]);

                    return $this->redirect(["site/login"]);
                } else {
                    return $this->render("nueva_contrasena", array('model' => $model));
                }
            } else {
                return $this->render("nueva_contrasena", array('model' => $model));
            }
        } else if (isset($_GET['hash']) && isset($_GET['id']) && sha1('logisticapolitecnicojic') == $_GET['hash']) {
            $Actor = \app\models\Actor1::findOne(["ID_ACTOR" => $_GET['id'], "NM_ESTADO_ID" => \app\models\EstadoActor::PENDIENTE_RESTAURAR_CONTRASENA]);
            if (!is_null($Actor)) {
                $Actor->scenario = \app\models\Actor1::SCENARIO_SAVE_TARE_CREDENTIALS;
                $Actor->DS_CONTRASENA = "";
                return $this->render("nueva_contrasena", array('model' => $Actor));
            } else {
                Yii::$app->getSession()->setFlash('error', ['type' => 'error',
                    'duration' => 5000,
                    'icon' => 'fa fa-users',
                    'message' => Yii::t('app', \yii\bootstrap\Html::encode('Este Actor no tiene solicitudes para cambio de contraseña o posiblemente no exista.')),
                    'title' => Yii::t('app', \yii\bootstrap\Html::encode('Error')),]);

                return $this->redirect(["site/login"]);
            }
        } else {
            Yii::$app->getSession()->setFlash('error', ['type' => 'error',
                'duration' => 5000,
                'icon' => 'fa fa-users',
                'message' => Yii::t('app', \yii\bootstrap\Html::encode('Usted no se encuentra autorizado para realizar esta acción.')),
                'title' => Yii::t('app', \yii\bootstrap\Html::encode('Error')),]);

            return $this->redirect(["site/login"]);
            $this->render('application.views.site.error');
        }
    }

    /**
     * Logout action.
     *

views/site/_isntaladores.php
<h2>Nodo Cliente para Windows</h2>
<p>Este archivo descarga la carpeta donde esta almacenado la información del nodo que sincroniza la BlockChain.</p>
<p>Al descargar el archio "Nodo Windows.rar" se visualizarán los siguientes archivos: </p>
<ol>
	<li>En la carpeta "nodo1" se encuentra almacenada la BlockChain.</li>
	<li>El archivo "genesis.json" se encuentra la configuración del primer bloque de la cadena.</li>
	<li>El ejecutable "geth.exe" es el software del servicio de la BlockChain.</li>
	<li>El ejecutable "Nodo instalación.bat", es el software encargado de instalar el nodo inicial "solo se ejecuta una sola vez".</li>
	<li>El ejecutable "Nodo ejecución.bat", es el software encargado de ejecutar el nodo.</li>
</ol>
<a href="documentos/Nodo Windows.rar">Descarga Nodo Cliente</a>
<br/>

<h2>Interfa gráfica MIST para la conexión del nodo principal</h2>

<p>MIST es un software con entorno gráfico que visualiza lo correspondiente al manejo de una BlockChain en Ethereum. Este programa es opcional para visualizar nuestro nodo privado.</p>

<p>Al descargar el archio "MIST Nodo.rar" se visualizarán los siguientes archivos: </p>
<ol>
	<li>El ejecutable "MIST Nodo.bat", es el software encargado de conectarse al nodo principal de forma gráfica.
</li>
</ol>
<ul>
<li><a href="https://github.com/ethereum/mist/releases/download/v0.11.1/Mist-installer-0-11-1.exe">Descarga MIST</a></li>
<li><a href="https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.8.23-c9427004.exe">Descarga Geth</a></li>
<li><a href="documentos/MIST Nodo.rar">Descarga MIST Nodo</a></li>
</ul>

views/site/_manuales_instalaciones.php
<?php
//$this->title = Yii::t('app', 'Manuales');
?>
<br/>
<ul>
	<li><a target="_blank" href="/documentos/MANUAL DE USUARIO.pdf">Manual de usuario</a></li>
	<!--<li><a target="_blank" href="documentos/MANUAL DE INSTALACIÓN.pdf">Manual de Instalaciones</a></li>-->
</ul>

views/site/_videos.php
<h3>Explicación del funcionamiento del aplicativo</h3>
<div style="text-align: center;"><br/><iframe src="https://drive.google.com/file/d/1S0XBl3HCo1fCNm2DazGp0F6UIo0xQ7HY/preview" width="640" height="480"></iframe></div>



<h3>Instalación del aplicativo web</h3>
<div style="text-align: center; display: block;"> <iframe src="https://drive.google.com/file/d/11x-F5nnOBAkhjqhJGjWwdTOFlKp6MV8g/preview" width="640" height="480"></iframe></div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Acerca de';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
   <center><h2>Sistema de Gestión Logística</h2>
    <p>Software para la gestión de logística<br/>
Trabajo de Grado, Ingeniería Informática<br/>
<table border="0">
	<tr><td  style="vertical-align: top">
Estudiantes</td>
<td>
<ul><li>Oscar Mesa</li><li>Joseph Ortiz</li></ul>
</td>
</tr>

	<tr><td  style="vertical-align: top">
Docentes</td>
<td>
<ul><li>Isabel Cristina Arango Palacio</li><li>Gladis Elena Velázquez</li></ul>
</td>
</tr>
</table>
	<br/>
Politécnico Colombiano Jaime Isaza Cadavid<br/>
    2019</p></center>
</div>

views/site/acercade.php
<?php

$this->title = Yii::t('app', 'Acerca se');

echo yii\bootstrap\Tabs::widget([
    'items' => [
        [
            'label' => 'Manual',
            'content' => '<iframe src="https://docs.google.com/viewer?srcid=1X9lWag9Y43F1ndwn8MVdyhya591VdBAa&pid=explorer&efh=false&a=v&chrome=false&embedded=true" style="width: 100%; height: 650px"></iframe>',
            'active' => true
        ],
        [
            'label' => 'Video',
            'content' => '<div style="text-align: center;padding-top:30px;"><iframe width="560" height="315" src="https://www.youtube.com/embed/eNLr9kRW7rY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
        ],
    
    ],
]);
?>

views/site/ayuda.php
<?php

$this->title = Yii::t('app', 'Ayudas');



echo yii\bootstrap\Tabs::widget([
    'items' => [        
        [
            'label' => 'Manuales',
            'content' => $this->render("_manuales_instalaciones"),
        ],
        /*[
            'label' => 'Instaladores',
            'content' => $this->render("_isntaladores"),
        ],
        [
            'label' => 'Videos',
            'content' => $this->render("_videos"),
        ],*/
    
    ],
]);

?>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Presentación';
?>
<style>

</style>
<div class="site-index">

    <!--<div class="jumbotron">
        <h1>Bienvenido!</h1>

        <p class="lead">Esta aplicación será util para la administración de productos, su venta y almacenamiento en la tienda.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div> -->

    <div class="body-content">

        <?php
use easyrider7522\yii2btswidget\Carousel;
?>
<div class="site-index">
    <div>
<?= Carousel::widget([
    'options'               => [                            // Widget container attributes.
        'id'                    => 'bootstrap-touch-slider',    // Slider (carousel) id.
        'class'                 => [                            // Array keys are used for possibility to override all the classes present by default.
            'bootstrap'             => 'carousel',                  // Bootstrap carousel style. Should not be changed.
            'widget'                => 'bs-slider',                 // Widget style.
            'effect'                => 'fade',                      // Slide effect.
            'controls'              => 'control-round',             // Left/Right controls styling.
            'indicators'            => 'indicators-line',           // Slide indicator styling.
        ],                                                      // Only the values are rendered (`class="carousel bs-slider fade control-round indicators-line"`).
        'data'                  => [                            // Data attibutes for Bootstrap JS.
            'ride'                  => 'carousel',                  // Animation starts at page load.
            'pause'                 => 'hover',                     // Cycling stops on hovering mouse.
            'interval'              => 'false',                     // Cycling delay.
        ],                                                      // For full specification see https://getbootstrap.com/docs/3.3/javascript/#carousel .
    ],
    'indicatorOptions'      => [                            // array|false Options of the wrapper of the slide indicators.
        'class'                 => 'carousel-indicators',
    ],
    'controlOptions'        => [                            // array|true|false Settings for left/right controls.
        'class'                 => 'carousel-control',          // Wrapper class.
        'leftArrow'             => 'angle-left',                // Font Awesome symbol for the left arrow.
        'rightArrow'            => 'angle-right',               // Font Awesome symbol for the right arrow.
    ],
    'slideWrapperOptions'   => [                            // Slide wrapper <div> options
        'class'                 => 'carousel-inner',
        'role'                  => 'listbox',
    ],
    'startSlide'            => 0,                           // The slide the animation starts with (index in the `slides` array).
    'slideOverlayOptions'   => [                            // The overlay <div> options
        'class'                 => 'bs-slider-overlay',         // Class of the overlay
    ],
    'slides'                => [                            // Array containing slides data.
        '@web/images/img70.jpg?v=1'=> [                           // Image web path. Aliases can be used, e.g. `@web/images/slider/slide1.jpeg`.
           // 'alt'                   => 'A carousel slide image 1',  // `alt` attribute contents of the <img> tag.
           /* 'textArea'              => [                            // array Settings for the overlaying text area.
                'align'                 => 'left',                      // string left|center|right Horizontal alignment of the text area.
                'header'                => 'Bootstrap Carousel',        // Header contents.
                'headerAnimation'       => 'zoomInRight',               // Header animation (see https://daneden.github.io/animate.css/ for variants).
                'text'                  => 'Bootstrap carousel now touch enabled slide.',   // Text paragraph contents.
                'textAnimation'         => 'fadeInLeft',                // Text paragraph animation.
                'buttons'               => [                            // array|false Some buttons below the text paragraph can be placed.
                    'select one'            => [                            // array Button caption (inner contents of the <a> tag).
                        'href'                  => '#',                         // Where the link points (`href` attribute of the <a> tag).
                        'type'                  => 'default',                   // In this case its class will become `btn btn-default` (see Bootstrap variants or define one).
                        'animation'             => 'fadeInLeft',                // Buttons can be also animated at appearance.
                        'target'                => '_blank',                    // Other acceptable <a> tag attributes can be added as done here.
                    ],
                    'select two'            => [
                        'href'                  => '#',
                        'type'                  => 'primary',
                        'animation'             => 'fadeInRight',
                        'target'                => '_blank',
                    ],
                ],
            ], */
        ],
        '@web/images/img40.jpg?v=1'=> [ ],
        //'@web/images/img42.jpg'=> [ ],
        '@web/images/img50.jpg?v=1'=> [ ],
        '@web/images/slide7.PNG?v=1'=> [ ],
      //  '@web/images/slide8.PNG'=> [ ],
       /* '@web/images/slide2.jpeg'=> [
            'alt'                   => 'A carousel slide image 2',
            'textArea'              => [
                'align'                 => 'center',
                'header'                => 'Bootstrap touch slider',
                'headerAnimation'       => 'flipInX',
                'text'                  => 'Make Bootstrap Better together.',
                'textAnimation'         => 'lightSpeedIn',
                'buttons'               => [
                    'select three'          => [
                        'url'                   => '#',
                        'type'                  => 'default',
                        'animation'             => 'fadeInUp',
                        'target'                => '_blank',
                    ],
                    'select four'           => [
                        'url'                   => '#',
                        'type'                  => 'primary',
                        'animation'             => 'fadeInDown',
                        'target'                => '_blank',
                    ],
                ],
            ],
        ],
        '@web/images/slide3.jpeg'=> [
            'alt'                   => 'A carousel slide image 3',
            'textArea'              => [
                'align'                 => 'right',
                'header'                => 'Beautiful Animations',
                'headerAnimation'       => 'zoomInLeft',
                'text'                  => 'Lots of css3 Animations to make slide beautiful.',
                'textAnimation'         => 'fadeInRight',
                'buttons'               => [
                    'select five'           => [
                        'url'                   => '#',
                        'type'                  => 'default',
                        'animation'             => 'fadeInLeft',
                        'target'                => '_blank',
                    ],
                    'select six'            => [
                        'url'                   => '#',
                        'type'                  => 'primary',
                        'animation'             => 'fadeInRight',
                        'target'                => '_blank',
                    ],
                ],
            ],
        ],*/
    ],
]);?>
    </div>
</div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor complete los siguientes campos para iniciar sesión:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        <?= Yii::t("app", "Si no tienes cuenta, {registrate}",[
            "registrate" => \yii\bootstrap\Html::a("registrate", "site/regitrar")
        ]) ?>
    </div>
</div>

views/site/nueva_contrasena.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */
$this->title = Yii::t('app', 'Restaurar Credenciales');
?>
<div class="login-box" style="width: auto;margin: 7% auto;padding-left: 15%;padding-right: 15%;">
    <h3>Hola <b><?= $model->DS_NOMBRES_ACTOR; ?></b>, por favor realiza el cambio de la contraseña. </h3>
    <div class="usuario-form box box-primary">
        <?php $form = yii\bootstrap\ActiveForm::begin(); ?>
        <div class="box-body table-responsive" style="overflow: hidden;">
            <div class="form-row">
                <div class="row">
                    <div class="col col-md-6">
                        <?= $form->field($model, 'DS_CONTRASENA')->passwordInput() ?>
                    </div>
                    <div class="col col-md-6">
                        <?= $form->field($model, 'CONFIRMAR_CONTRASENA')->passwordInput() ?>
                    </div>
                    <div style="display:none" class="col col-md-6">
                    <?= $form->field($model, 'ID_ACTOR')->hiddenInput() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('app', 'Guardar'), ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php yii\bootstrap\ActiveForm::end(); ?>
</div>

views/site/verifikasi.php
<?php
$this->pageTitle=Yii::app()->name . ' - Change Password';
$this->breadcrumbs=array(
	'Change Password',
);
?>
<h2>Hi! <?php echo $model->nama_asli;?> :v</h2>
<div class="form">
    <h2>Change Password</h2>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'Ganti-form',
)); ?>

	<div class="row">
            New Password : <input name="Ganti[password]" id="ContactForm_email" type="password">
            <input name="Ganti[tokenhid]" id="ContactForm_email" type="hidden" value="<?php echo $model->token?>">
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->